sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedkhaledre/docker-react -f Dockerfile.dev .

script:
  - docker run ahmedkhaledre/docker-react npm run test -- --coverage


before_deploy:
  - npm install netlify-cli -g
  - npm run build

deploy:
  provider: script
  script: netlify deploy -s loving-murdock-1be57f -t $FIRST_REACT_DOCKER -p ./build
  skip_cleanup: true
  on:
    branch: master