sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedkhaledre/docker-react -f Dockerfile.dev .

script:
  - docker run ahmedkhaledre/docker-react npm run test -- --coverage

  deploy:
    provider: netlify
    site: loving-murdock-1be57f
    auth: FIRST_REACT_DOCKER
    edge: true # opt in to dpl v2